/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export const TCC_CONCEPTS = {
  NecessidadesInfantis: [
    { name: "Atenção", desc: "Necessidade básica de ser notada, vista e percebida pelos cuidadores como um ser individual e importante." },
    { name: "Carinho", desc: "Necessidade de afeto físico, proximidade emocional, ternura e expressões calorosas de amor." },
    { name: "Admiração", desc: "Necessidade de ser valorizada, elogiada e reconhecida em suas conquistas e qualidades únicas." },
    { name: "Vínculo", desc: "Sentimento profundo de conexão, pertencimento e segurança dentro de um grupo familiar ou social." },
    { name: "Proteção", desc: "Sentimento de segurança física e emocional; saber que há alguém para amparar contra perigos." },
    { name: "Cuidado", desc: "Suporte consistente nas necessidades biológicas e emocionais básicas (nutrição, higiene, consolo)." },
    { name: "Autonomia", desc: "Incentivo e permissão para desenvolver independência, agência própria e capacidade de escolha." },
    { name: "Sociabilidade", desc: "Capacidade e oportunidade de interagir, trocar experiências e brincar com pares de forma saudável." },
    { name: "Conversação", desc: "Espaço para dialogar, ser ouvido sem julgamento e expressar o mundo interno de forma aberta." },
    { name: "Instrução", desc: "Sentir-se inteligente, capaz de aprender e receber orientação adequada sobre o funcionamento do mundo." },
    { name: "Diversão", desc: "Oportunidade de brincar, explorar, ser criativo e vivenciar o prazer sem cobranças de desempenho." },
    { name: "Responsabilidade", desc: "Aprendizado gradual sobre limites, consequências dos próprios atos e compromisso com o outro." },
    { name: "Gregariedade", desc: "Sentir que sua presença agrega valor e que você é uma peça importante na vida das pessoas." },
    { name: "Identidade", desc: "Construção de um autoconceito claro, sólido e diferenciado das expectativas de terceiros." },
    { name: "Compreensão", desc: "Sentir-se compreendido em sua essência, tendo suas emoções validadas e empatizadas." }
  ],
  Esquemas: [
    { 
      name: "Abandono/Instabilidade", 
      desc: "Percepção de que as pessoas significativas não serão capazes de continuar fornecendo suporte emocional, conexão ou proteção prática porque são emocionalmente instáveis, imprevisíveis, morrerão em breve ou abandonarão o paciente por alguém melhor.", 
      for: ["nao_amabilidade", "incapacidade"],
      peripherals: ["Regra: Eu devo sempre estar alerta para sinais de rejeição", "Pressuposto: Se eu confiar em alguém, essa pessoa eventualmente irá embora"],
      excesses: ["Busca incessante de reasseguramento", "Verificação constante do paradeiro de terceiros", "Ciúmes excessivo", "Clamores emocionais"],
      deficits: ["Autorregulação emocional", "Imunidade social", "Capacidade de ficar sozinho"],
      history: ["Morte de um dos pais ou divórcio conflituoso na infância", "Pais emocionalmente instáveis ou com dependência química", "Internações hospitalares prolongadas sem acompanhante"]
    },
    { 
      name: "Desconfiança/Abuso", 
      desc: "Expectativa de que os outros irão maltratar, humilhar, enganar, mentir, manipular ou tirar vantagem. Frequentemente envolve a crença de que o dano é intencional ou resultado de negligência extrema e injustificada.", 
      for: ["desvalor"],
      peripherals: ["Regra: Nunca baixar a guarda", "Atitude: Desconfiança perante elogios"],
      excesses: ["Sarcasmo e ironia como defesa", "Testar a lealdade dos outros constantemente", "Agressividade preventiva"],
      deficits: ["Vulnerabilidade compartilhada", "Intimidade emocional", "Colaboração"],
      history: ["Histórico de abuso físico, sexual ou psicológico", "Família onde membros usavam uns aos outros", "Bullying severo onde não houve proteção dos adultos"]
    },
    { 
      name: "Privação Emocional", 
      desc: "Expectativa de que os desejos de um grau normal de apoio emocional não serão adequadamente atendidos pelos outros. Pode envolver privação de cuidado (falta de atenção/afeto), privação de empatia (não ser compreendido) ou privação de proteção (falta de orientação/direção).", 
      for: ["nao_amabilidade"],
      peripherals: ["Pressuposto: Ninguém nunca vai realmente me entender ou cuidar de mim", "Regra: Eu devo me virar sozinho, pois não há apoio"],
      excesses: ["Reclamação passiva sobre falta de atenção", "Escolha de parceiros emocionalmente frios ou indisponíveis"],
      deficits: ["Expressão de necessidades emocionais", "Autoconhecimento afetivo"],
      history: ["Mãe/Pai emocionalmente frios ou distantes", "Criança que precisou cuidar dos pais emocionalmente (parentalização)", "Família sem demonstrações de afeto físico ou verbal"]
    },
    { 
      name: "Defectividade/Vergonha", 
      desc: "Sentimento de que se é defeituoso, mau, indesejado, inferior ou inválido em aspectos importantes, ou de que se seria impalatável para as pessoas significativas se exposto. Pode envolver hipersensibilidade a críticas, rejeição e culpa; autoconsciência exagerada e insegurança.", 
      for: ["desvalor", "nao_amabilidade"],
      peripherals: ["Regra: Esconder meus verdadeiros sentimentos/defeitos", "Pressuposto: Se me conhecerem de verdade, vão me rejeitar"],
      excesses: ["Uso de 'máscaras' sociais", "Perfecionismo para compensar a falha interna", "Compensação através de status ou bens"],
      deficits: ["Autoesteem incondicional", "Imunidade social", "Autenticidade"],
      history: ["Críticas constantes e humilhações por parte dos cuidadores", "Ser comparado negativamente com irmãos ou pares", "Rejeição parental explícita"]
    },
    { 
      name: "Isolamento Social", 
      desc: "Sentimento de que se é isolado do resto do mundo, diferente das outras pessoas e/ou de que não se faz parte de qualquer grupo ou comunidade. Crença de que é 'estranho' ou que não pertence.", 
      for: ["nao_amabilidade"],
      peripherals: ["Regra: Eu devo evitar situações sociais onde eu possa parecer diferente", "Atitude: Eu sou um observador externo da vida"],
      excesses: ["Hipervigilância a sinais de exclusão", "Mimetismo social (fingir ser igual aos outros)"],
      deficits: ["Sentimento de pertencimento", "Habilidades sociais de integração", "Espontaneidade"],
      history: ["Família que se sentia diferente ou superior/inferior ao resto da comunidade", "Mudar-se muito de cidade/país na infância", "Ter uma característica física ou cultural que gerava exclusão"]
    },
    { 
      name: "Dependência/Incompetência", 
      desc: "Crença de que se é incapaz de lidar com as responsabilidades cotidianas de forma competente sem ajuda considerável dos outros (ex: cuidar de si, resolver problemas diários, exercer bom julgamento, lidar com novas tarefas). Muitas vezes se apresenta como um desamparo.", 
      for: ["incapacidade"],
      peripherals: ["Regra: Eu devo sempre consultar alguém antes de decidir", "Pressuposto: Sozinho eu vou fracassar miseravelmente"],
      excesses: ["Solicitação constante de ajuda para tarefas simples", "Procrastinação por medo de decidir errado"],
      deficits: ["Habilidade de decisão", "Autonomia prática", "Confiança no próprio julgamento"],
      history: ["Superproteção extrema (pais que faziam tudo pela criança)", "Pais que criticavam as tentativas de independência", "Ser impedido de assumir responsabilidades adequadas à idade"]
    },
    { 
      name: "Vulnerabilidade", 
      desc: "Medo excessivo de que catástrofes iminentes (médicas, financeiras, naturais ou criminais) ocorrerão a qualquer momento e de que não se será capaz de impedi-las. Sentimento de estar 'no limite' de um desastre.", 
      for: ["incapacidade"],
      peripherals: ["Regra: Eu devo estar sempre preparado para o pior", "Atitude: O mundo é um lugar extremamente perigoso"],
      excesses: ["Verificação obsessiva de sintomas de saúde", "Acúmulo de recursos ou segurança", "Evitação de lugares 'perigosos'"],
      deficits: ["Autorregulação da ansiedade", "Percepção realista de risco"],
      history: ["Crescer com pais fóbicos ou extremamente ansiosos", "Experiência de um trauma real súbito (doença grave na família, assalto, perda financeira brusca)"]
    },
    { 
      name: "Emaranhamento", 
      desc: "Envolvimento emocional excessivo e proximidade com um ou mais pessoas significativas (geralmente pais), à custa da individualização total ou do desenvolvimento social normal. Frequentemente envolve a convicção de que pelo menos um dos indivíduos emaranhados não consegue sobreviver ou ser feliz sem o apoio constante do outro.", 
      for: ["incapacidade"],
      peripherals: ["Regra: A felicidade do meu pai/mãe é minha responsabilidade", "Pressuposto: Se eu me afastar, algo terrível acontecerá a eles"],
      excesses: ["Compartilhamento de todos os detalhes da vida com os pais", "Dificuldade em ter segredos ou privacidade"],
      deficits: ["Identidade própria", "Limites interpessoais", "Autodeterminação"],
      history: ["Pais que usavam o filho como confidente emocional", "Pais que se faziam de vítimas para prender a criança", "Família onde a privacidade era vista como traição"]
    },
    { 
      name: "Fracasso", 
      desc: "Crença de que falhou, falhará inevitavelmente ou é fundamentalmente inadequado em relação aos pares em áreas de realização (escola, carreira, esportes). Envolve sentimentos de ser burro, sem talento ou de nível inferior.", 
      for: ["fracasso", "incapacidade"],
      peripherals: ["Regra: Eu tenho que me esforçar o triplo para ser apenas razoável", "Pressuposto: Eventualmente todos perceberão que sou uma fraude"],
      excesses: ["Trabalho compulsivo", "Sabotagem de oportunidades de sucesso", "Evitação de novos desafios"],
      deficits: ["Autoesteem ocupacional", "Persistência após o erro", "Comemoração de conquistas"],
      history: ["Pais muito bem-sucedidos e críticos", "Dificuldades de aprendizado não diagnosticadas na infância", "Ser rotulado como o 'burro' da família"]
    },
    { 
      name: "Grandiosidade", 
      desc: "Crença de que se é superior às outras pessoas, com direito a privilégios especiais, ou de que não se está sujeito às regras de reciprocidade que orientam a interação social normal.", 
      for: ["desvalor"],
      peripherals: ["Regra: Eu não deveria ter que esperar em filas", "Atitude: As pessoas são ferramentas para meus objetivos"],
      excesses: ["Interrupção de conversas", "Comportamento exigente e impaciente", "Falta de empatia"],
      deficits: ["Empatia", "Reciprocidade social", "Autocontrole"],
      history: ["Ser o 'filho de ouro' que nunca recebia limites", "Compensação de um sentimento profundo de inferioridade", "Pais que usavam o status do filho para se sentirem importantes"]
    }
  ],
  CrencasCentrais: [
    { name: "Incapacidade", desc: "Núcleo de desamparo: 'Eu sou incompetente', 'Eu não consigo lidar com a vida', 'Sou vulnerável', 'Sou fraco'.", id: "incapacidade" },
    { name: "Não-amabilidade", desc: "Núcleo de rejeição: 'Eu sou indesejável', 'Ninguém vai me querer', 'Sou chato', 'Serei sozinho para sempre'.", id: "nao_amabilidade" },
    { name: "Desvalor", desc: "Núcleo de indignidade: 'Não tenho valor', 'Sou um impostor', 'Sou uma pessoa má', 'O mundo é um lugar cruel'.", id: "desvalor" },
    { name: "Fracasso", desc: "Crença central de incompetência generalizada: 'Eu sou um fracassado', 'Nada que eu faço dá certo'.", id: "fracasso" }
  ],
  CrencasPerifericas: [
    { name: "Perfeccionismo", desc: "Regra: 'Se eu não for perfeito, ninguém vai me amar.'", cat: "nao_amabilidade" },
    { name: "Desconfiança Preventiva", desc: "Regra: 'Se eu mostrar fraqueza, as pessoas vão se aproveitar.'", cat: "desvalor" },
    { name: "Alerta Catastrófico", desc: "Regra: 'O mundo é perigoso e eu devo estar sempre alerta.'", cat: "incapacidade" },
    { name: "Dependência de Apoio", desc: "Regra: 'Eu não consigo sobreviver sem o apoio de alguém mais forte.'", cat: "incapacidade" },
    { name: "Evitação de Riscos", desc: "Regra: 'Se eu tentar e falhar, isso prova que sou um fracasso.'", cat: "fracasso" },
    { name: "Sucessismo Extremado", desc: "Regra: 'Eu só tenho valor se eu for o melhor em tudo.'", cat: "desvalor" },
    { name: "Subjugação por Medo", desc: "Regra: 'Eu devo fazer o que os outros querem para evitar que me deixem.'", cat: "nao_amabilidade" },
    { name: "Escaneamento de Rejeição", desc: "Regra: 'Eu devo estar sempre atento a sinais de que as pessoas estão se cansando de mim.'", cat: "nao_amabilidade" },
    { name: "Autosuficiência Rígida", desc: "Regra: 'Não posso pedir ajuda, pois isso mostra que sou incompetente.'", cat: "incapacidade" },
    { name: "Necessidade de Controle", desc: "Regra: 'Tenho que controlar tudo ao meu redor para que nada saia errado.'", cat: "incapacidade" }
  ],
  TranstornosTopograficos: [
    { 
      name: "Depressão Maior",
      functionalName: "Transtorno por Desamparo Generalizado",
      desc: "Humor deprimido, redução do interesse e prazer, sentimentos de desvalia ou culpa.",
      history: ["Histórico de extinção e punição generalizadas", "Histórico punitivo verbal modelando regras de desamor e desvalor"],
      cognitions: ["Sou um fracassado", "Nada que eu faça vai mudar as coisas", "Tudo dará errado"],
      maintaining: ["Reforçamento negativo por evitação de tarefas aversivas", "Reforçamento social"],
      behaviors: ["Humor deprimido", "Redução do interesse e prazer"],
      deficits: ["Habilidades psicológicas básicas", "Ativação comportamental"],
      newSkills: ["Ativação Comportamental", "Auto-validação"],
      schemes: ["Privação Emocional", "Defectividade/Vergonha", "Fracasso"],
      coreBeliefs: ["Sou um fracassado", "Não tenho valor"],
      peripheralBeliefs: ["Se eu me esforçar, não vai adiantar", "Melhor nem tentar"]
    },
    { 
      name: "Transtorno Bipolar",
      functionalName: "Transtorno por Responsividade a Sinalizadores Armadilosos Alternado com Desamparo Generalizado",
      desc: "Alternância entre episódios de mania (grandiosidade) e depressão.",
      history: ["Déficit na modelagem de variabilidade", "Estado severo de privação"],
      cognitions: ["Posso tudo e quero agora", "Sou um inconsequente irresponsável"],
      maintaining: ["Reforçamento imediato das armadilhas", "Reforçamento social"],
      behaviors: ["Grandiosidade", "Distratibilidade", "Comportamentos hedonistas viciosos"],
      deficits: ["Autoconhecimento", "Raciocínio Realisticamente Otimista"],
      newSkills: ["Autocontrole", "Autorregulação Emocional"],
      schemes: ["Grandiosidade", "Autocontrole Insuficiente"],
      coreBeliefs: ["Eu sou especial", "Eu sou perigoso para mim mesmo"],
      peripheralBeliefs: ["As regras não se aplicam a mim", "Eu devo aproveitar cada impulso"]
    },
    { 
      name: "Transtornos de Controle do Impulso (Compulsões)",
      functionalName: "Transtorno por Obtenção de Reforçadores Armadilosos",
      desc: "Dificuldade em resistir a um impulso prejudicial.",
      history: ["Déficits no controle por regras", "Baixa tolerância à frustração"],
      cognitions: ["Preciso ter isso agora", "Detesto me frustrar"],
      maintaining: ["Reforçamento imediato", "Reforçamento negativo por evitação"],
      behaviors: ["Padrão incontrolável de acesso e envolvimento com fontes de prazer"],
      deficits: ["Autocontrole", "Diferimento de gratificação"],
      newSkills: ["Tolerância à Frustração", "Diferimento de Gratificação"],
      schemes: ["Autocontrole Insuficiente"],
      coreBeliefs: ["Eu não consigo me controlar", "Eu preciso de prazer para suportar a vida"],
      peripheralBeliefs: ["Se eu não tiver o que quero, vou explodir"]
    },
    { 
      name: "Fobia Específica",
      functionalName: "Transtorno por Remoção de Estimulação Aversiva Exteroceptiva Específica",
      desc: "Medo acentuado e persistente de um objeto ou situação específica.",
      history: ["Condicionamento respondente aversivo", "Modelagem punitiva"],
      cognitions: ["Vou me machucar", "É perigoso"],
      maintaining: ["Reforçamento negativo pela evitação do estímulo fóbico"],
      behaviors: ["Medo acentuado", "Ansiedade imediata", "Evitação sistemática"],
      deficits: ["Autorregulação Emocional", "Raciocínio Realisticamente Otimista"],
      newSkills: ["Exposição Gradual", "Tolerância ao Mal-estar"],
      schemes: ["Vulnerabilidade ao Dano"],
      coreBeliefs: ["Sou frágil", "O mundo é perigoso"],
      peripheralBeliefs: ["Devo evitar qualquer contato com o perigo"]
    },
    { 
      name: "Ansiedade Social",
      functionalName: "Transtorno por Remoção de Estimulação Aversiva Social",
      desc: "Medo intenso de ser julgado ou rejeitado em situações sociais.",
      history: ["Inibição comportamental", "Pais autoritários e subjugadores"],
      cognitions: ["As pessoas vão me criticar", "Vou ser humilhado"],
      maintaining: ["Reforçamento negativo por evitar punição social"],
      behaviors: ["Medo de ser visto comportando-se de modo embaraçoso"],
      deficits: ["Imunidade Social", "Autoestima"],
      newSkills: ["Sociabilidade", "Treino de Assertividade"],
      schemes: ["Isolamento Social", "Defectividade/Vergonha"],
      coreBeliefs: ["Sou inadequado", "As pessoas são críticas"],
      peripheralBeliefs: ["Se eu falar, vão rir de mim"]
    },
    { 
      name: "Transtorno do Pânico",
      functionalName: "Transtorno por Remoção de Estimulação Aversiva Interoceptiva",
      desc: "Ataques de pânico inesperados e medo de novos ataques.",
      history: ["Superproteção familiar", "Excesso de estimulação aversiva"],
      cognitions: ["Vou morrer", "Vou enlouquecer"],
      maintaining: ["Reforçamento negativo por evitar desconforto privado"],
      behaviors: ["Palpitações", "Tremores", "Falta de ar"],
      deficits: ["Autorregulação Emocional", "Resolutividade"],
      newSkills: ["Interocepção Saudável", "Normatização de Sensações"],
      schemes: ["Vulnerabilidade ao Dano"],
      coreBeliefs: ["Meu corpo é frágil", "Estou em perigo"],
      peripheralBeliefs: ["Qualquer sensação estranha é um desastre"]
    },
    { 
      name: "Agorafobia",
      functionalName: "Transtorno por Desamparo sob Circunstâncias Inescapáveis",
      desc: "Ansiedade de estar em locais onde a fuga possa ser difícil.",
      history: ["Condicionamento aversivo em contextos de inescapabilidade"],
      cognitions: ["Preciso estar em segurança", "Não vou conseguir sair"],
      maintaining: ["Reforçamento negativo por evitar desconforto"],
      behaviors: ["Evitação de lugares onde a fuga possa ser difícil"],
      deficits: ["Autoestima", "Resolutividade"],
      newSkills: ["Exposição com Prevenção de Resposta", "Autonomia Geográfica"],
      schemes: ["Dependência/Incompetência", "Vulnerabilidade"],
      coreBeliefs: ["Estou desamparado", "Preciso de proteção"],
      peripheralBeliefs: ["Só estou seguro em casa"]
    },
    { 
      name: "TEPT (Transtorno de Estresse Pós-Traumático)",
      functionalName: "Transtorno por Desamparo sob Estimulação Aversiva Generalizada após Pareamento Agudo",
      desc: "Desenvolvimento de sintomas após exposição a evento traumático.",
      history: ["Experiência de trauma real súbito e intenso"],
      cognitions: ["A qualquer momento algo ruim pode acontecer"],
      maintaining: ["Reforçamento negativo por evitar recordações"],
      behaviors: ["Flashbacks", "Recordações aflitivas", "Hipervigilância"],
      deficits: ["Autorregulação Emocional", "Resiliência"],
      newSkills: ["Processamento de Trauma", "Resiliência Psicológica"],
      schemes: ["Desconfiança/Abuso", "Vulnerabilidade"],
      coreBeliefs: ["As pessoas são perigosas", "Eu sou vulnerável"],
      peripheralBeliefs: ["Nunca devo baixar a guarda"]
    },
    { 
      name: "TAG (Transtorno de Ansiedade Generalizada)",
      functionalName: "Transtorno por Desamparo e Remoção de Estimulação Aversiva Generalizada Estabelecida por Regras",
      desc: "Preocupação excessiva e constante sobre diversas áreas.",
      history: ["Histórico de superproteção parental"],
      cognitions: ["Há perigo em todo lugar", "Tenho que me preocupar"],
      maintaining: ["Reforçamento negativo pela evitação da incerteza"],
      behaviors: ["Preocupação excessiva", "Tensão motora"],
      deficits: ["Raciocínio Realisticamente Otimista", "Foco no presente"],
      newSkills: ["Resolutividade e Enfrentamento", "Foco no Presente"],
      schemes: ["Vulnerabilidade ao Dano", "Busca de Aprovação"],
      coreBeliefs: ["Eu não consigo lidar com a incerteza", "O mundo é perigoso"],
      peripheralBeliefs: ["Se eu me preocupar, evito o pior"]
    },
    { 
      name: "TOC (Transtorno Obsessivo-Compulsivo)",
      functionalName: "Transtorno por Remoção Contígua de Estimulação Aversiva Estabelecida por Regras",
      desc: "Presença de obsessões e compulsões que consomem tempo.",
      history: ["Modelagem de regras distorcidas e ameaçadoras"],
      cognitions: ["Se eu não fizer isso, algo ruim pode acontecer"],
      maintaining: ["Reforçamento negativo pela cessação da obsessão"],
      behaviors: ["Obsessões", "Compulsões (rituais)"],
      deficits: ["Flexibilidade Cognitiva", "Autorregulação Emocional"],
      newSkills: ["Exposição com Prevenção de Resposta", "Flexibilidade Cognitiva"],
      schemes: ["Padrões Inflexíveis", "Punitividade"],
      coreBeliefs: ["Sou responsável por desastres", "Pensamentos são fatos"],
      peripheralBeliefs: ["Devo ser perfeito para evitar danos"]
    },
    { 
      name: "Transtorno da Compulsão Alimentar",
      functionalName: "Transtorno do Reforçamento Alimentar Armadiloso",
      desc: "Episódios de consumo excessivo de comida com perda de controle.",
      history: ["Uso do alimento para supressão emocional"],
      cognitions: ["Comer é o que me acalma", "Não consigo resistir"],
      maintaining: ["Reforçamento positivo imediato do prazer", "Supressão de sentimentos negativos"],
      behaviors: ["Ataques de comer", "Comer escondido"],
      deficits: ["Autocontrole", "Autorregulação Emocional"],
      newSkills: ["Alimentação Consciente", "Gestão de Gatilhos"],
      schemes: ["Autocontrole Insuficiente"],
      coreBeliefs: ["Eu sou fraco", "Eu sou indesejável"],
      peripheralBeliefs: ["Se estou triste, comer resolve"]
    },
    { 
      name: "Anorexia Nervosa",
      functionalName: "Transtorno de Evitação do Ganho de Peso por Pareamento com Punição Social",
      desc: "Recusa em manter o peso normal, medo intenso de engordar.",
      history: ["Apelo midiático estético", "Punição social da obesidade"],
      cognitions: ["Ser magro é ter valor", "Se eu engordar serei rejeitada"],
      maintaining: ["Reforçamento negativo pela fuga da punição social"],
      behaviors: ["Restrição alimentar severa", "Visão distorcida do corpo"],
      deficits: ["Autoestima", "Imunidade Social"],
      newSkills: ["Aceitação Corporal", "Valorização Interna"],
      schemes: ["Defectividade/Vergonha", "Padrões Inflexíveis"],
      coreBeliefs: ["Só serei amada se for magra", "Eu não tenho valor"],
      peripheralBeliefs: ["Controlar meu peso é controlar minha vida"]
    },
    { 
      name: "Bulimia Nervosa",
      functionalName: "Transtorno de Obtenção de Reforço Alimentar Armadiloso com Evitação do Ganho de Peso por Pareamento com Punição Social",
      desc: "Compulsão alimentar seguida de purgação.",
      history: ["Modelagem de métodos purgativos", "Uso da comida como alívio"],
      cognitions: ["Posso comer agora e depois eu me limpo"],
      maintaining: ["Reforçamento imediato", "Alívio da ansiedade pelo vômito"],
      behaviors: ["Binge eating", "Vômitos induzidos"],
      deficits: ["Autocontrole", "Autoestima"],
      newSkills: ["Equilíbrio Nutricional", "Autorregulação Afetiva"],
      schemes: ["Defectividade/Vergonha", "Autocontrole Insuficiente"],
      coreBeliefs: ["Eu sou um impostor", "Eu sou descontrolado"],
      peripheralBeliefs: ["O importante é manter a aparência externa"]
    },
    { 
      name: "Parafilias",
      functionalName: "Transtorno do Reforçamento Sexual Armadiloso",
      desc: "Interesses sexuais em objetos ou situações não convencionais.",
      history: ["Condicionamento sexual respondente atípico"],
      cognitions: ["Só agindo assim sinto prazer real"],
      maintaining: ["Reforçamento positivo sexual intenso"],
      behaviors: ["Fantasias e comportamentos sexuais parafílicos"],
      deficits: ["Autocontrole", "Empatia"],
      newSkills: ["Saúde Sexual Alternativa", "Direcionamento de Impulso"],
      schemes: ["Autocontrole Insuficiente", "Isolamento Social"],
      coreBeliefs: ["Eu sou esquisito", "Minha sexualidade é errada"],
      peripheralBeliefs: ["Eu não consigo prazer de formas normais"]
    },
    { 
      name: "Desejo Sexual Hipoativo",
      functionalName: "Transtorno por Extinção do Repertório Sexual",
      desc: "Ausência de fantasias e desejo sexual.",
      history: ["Histórico de punição ou tédio sexual"],
      cognitions: ["Sexo é uma obrigação chata"],
      maintaining: ["Reforçamento negativo por evitar situações sexuais"],
      behaviors: ["Evitação de intimidade", "Ausência de libido"],
      deficits: ["Hedonismo Responsável", "Vínculo"],
      newSkills: ["Educação Sexual Positiva", "Vínculo de Intimidade"],
      schemes: ["Privação Emocional", "Auto-sacrifício"],
      coreBeliefs: ["Eu não sou sexualmente atraente", "Minhas necessidades não importam"],
      peripheralBeliefs: ["Melhor evitar para não frustrar o outro"]
    },
    { 
      name: "Aversão Sexual",
      functionalName: "Transtorno de Evitação da Estimulação Sexual Aversiva por Pareamento ou Regra",
      desc: "Aversão extrema e evitação de contato sexual.",
      history: ["Histórico de abuso ou regras religiosas punitivas"],
      cognitions: ["Sexo é nojento", "Vou ser invadida"],
      maintaining: ["Reforçamento negativo pela fuga da estimulação aversiva"],
      behaviors: ["Ansiedade perante sexo", "Evitação total"],
      deficits: ["Autorregulação Emocional", "Raciocínio Realista"],
      newSkills: ["Dessensibilização Sexual", "Normatização do Prazer"],
      schemes: ["Desconfiança/Abuso", "Defectividade/Vergonha"],
      coreBeliefs: ["Sou vulnerável a abusos", "O sexo é mau"],
      peripheralBeliefs: ["Se eu me abrir sexualmente, serei ferida"]
    },
    { 
      name: "Excitação Feminina / Disfunção Erétil",
      functionalName: "Transtorno da Eliciação Concorrente com a Resposta Excitatória por Pareamento Aversivo",
      desc: "Dificuldade em manter a resposta física sexual.",
      history: ["Ansiedade de desempenho", "Regras machistas"],
      cognitions: ["Tenho que ser perfeito"],
      maintaining: ["Reforçamento negativo pela evitação da frustração"],
      behaviors: ["Perda da ereção ou lubrificação"],
      deficits: ["Raciocínio Realisticamente Otimista", "Autocontrole"],
      newSkills: ["Foco Sensorial", "Desconstrução de Performance"],
      schemes: ["Fracasso", "Defectividade"],
      coreBeliefs: ["Eu sou incompetente", "Eu não sou atraente"],
      peripheralBeliefs: ["Se eu falhar na cama, perderei meu valor"]
    },
    { 
      name: "Vaginismo",
      functionalName: "Transtorno de Evitação da Estimulação Penetrativa Aversiva por Pareamento ou Regra",
      desc: "Contração involuntária dos músculos vaginais que impede a penetração.",
      history: ["Histórico de coação sexual", "Regras sexuais distorcidas"],
      cognitions: ["Sexo é doloroso", "Vou me machucar"],
      maintaining: ["Reforçamento negativo por fuga da estimulação aversiva"],
      behaviors: ["Contração involuntária da musculatura vaginal"],
      deficits: ["Autorregulação Emocional", "Raciocínio Realista"],
      newSkills: ["Fisioterapia Pélvica", "Exercícios de Relaxamento"],
      schemes: ["Desconfiança/Abuso", "Vulnerabilidade"],
      coreBeliefs: ["O sexo é perigoso", "Meu corpo vai ser ferido"],
      peripheralBeliefs: ["Devo fechar meu corpo para me proteger"]
    },
    { 
      name: "Anorgasmia",
      functionalName: "Transtorno do Desamparo à Estimulação Sexual Aversiva ou Deficitária",
      desc: "Retardo ou ausência de orgasmo após fase de excitação.",
      history: ["Pareamento sexual aversivo", "Privação de reforçamento"],
      cognitions: ["Não sinto prazer", "Mesmo que eu tente, não vai dar"],
      maintaining: ["Reforçamento negativo pela fuga da punição social"],
      behaviors: ["Ausência ou retardo do orgasmo"],
      deficits: ["Autorregulação Emocional", "Resolutividade"],
      newSkills: ["Exploração Sensual", "Foco no Prazer Próprio"],
      schemes: ["Privação Emocional", "Fracasso"],
      coreBeliefs: ["Eu sou defeituosa", "Eu não consigo sentir prazer"],
      peripheralBeliefs: ["O prazer não é para mim"]
    },
    { 
      name: "Ejaculação Precoce",
      functionalName: "Transtorno da Estimulação Sexual Potenciada",
      desc: "Ejaculação com estimulação mínima, antes do desejado.",
      history: ["Filogênese hipersensibilizadora", "Regras de performance"],
      cognitions: ["Vou falhar de novo", "Serei considerado fraco"],
      maintaining: ["Reforçamento negativo pela fuga da frustração"],
      behaviors: ["Dificuldade de controlar a ejaculação"],
      deficits: ["Autocontrole", "Autorregulação Emocional"],
      newSkills: ["Técnicas de Controle Ejaculatório", "Redução de Ansiedade"],
      schemes: ["Fracasso", "Busca de Aprovação"],
      coreBeliefs: ["Eu sou incompetente", "Eu sou um fracasso como homem"],
      peripheralBeliefs: ["Eu tenho que satisfazer minha parceira imediatamente"]
    },
    { 
      name: "Personalidade Histriônica",
      functionalName: "Transtorno de Obtenção de Atenção e Cuidado",
      desc: "Padrão de excessiva emocionalidade e busca de atenção.",
      history: ["Excesso de reforço parental de comportamentos apelativos"],
      cognitions: ["Sou atraente e as pessoas não podem me negar atenção"],
      maintaining: ["Reforçamento positivo por atenção e adulação"],
      behaviors: ["Expressa emoções de modo teatral", "Utiliza aparência física"],
      deficits: ["Resolutividade", "Autorregulação Emocional"],
      newSkills: ["Autoestima Interna", "Limites Saudáveis"],
      schemes: ["Busca de Aprovação", "Privação Emocional"],
      coreBeliefs: ["Eu sou invisível se não for o centro", "Eu sou especial"],
      peripheralBeliefs: ["Se eu não chamar atenção, ninguém vai cuidar de mim"]
    },
    { 
      name: "Personalidade Obsessiva",
      functionalName: "Transtorno de Seguimento Indiscriminado de Regras para Evitação de Punição Social e Obtenção de Reforçamento Social",
      desc: "Preocupação com organização, perfeccionismo e controle.",
      history: ["Histórico de excessivo controle por regras"],
      cognitions: ["Existe uma forma única e certa de fazer"],
      maintaining: ["Reforçamento negativo pela fuga da punição por falhas"],
      behaviors: ["Preocupação com detalhes", "Perfeccionismo paralisante"],
      deficits: ["Flexibilidade Cognitiva", "Hedonismo Responsável"],
      newSkills: ["Flexibilidade Cognitiva", "Priorização de Prazer"],
      schemes: ["Padrões Inflexíveis", "Punitividade"],
      coreBeliefs: ["Sou imperfeito", "O mundo é caótico"],
      peripheralBeliefs: ["Devo controlar tudo para ser aceito"]
    },
    { 
      name: "Personalidade Antissocial",
      functionalName: "Transtorno de Obtenção Exploratória do Reforçamento Social",
      desc: "Padrão de desrespeito e violação dos direitos alheios.",
      history: ["Modelos violentos", "Ter sofrido agressões"],
      cognitions: ["Não se pode confiar em ninguém", "Na vida você bate ou apanha"],
      maintaining: ["Reforçamento negativo pela fuga de abusos", "Reforço imediato por usar os outros"],
      behaviors: ["Incapacidade de adaptar-se a normas", "Impulsividade"],
      deficits: ["Empatia", "Autocontrole"],
      newSkills: ["Desenvolvimento de Empatia", "Comportamento Pró-social"],
      schemes: ["Desconfiança/Abuso", "Arrogo/Grandiosidade"],
      coreBeliefs: ["As pessoas são ferramentas", "Eu sou o predador"],
      peripheralBeliefs: ["Se eu não tirar vantagem, tirarão de mim"]
    },
    { 
      name: "Personalidade Narcisista",
      functionalName: "Transtorno de Obtenção de Reconhecimento Social de Reconhecimento",
      desc: "Padrão de grandiosidade e necessidade de admiração.",
      history: ["Excesso de reforçamento de reconhecimento"],
      cognitions: ["Sou especial, único, mereço privilégios"],
      maintaining: ["Reforçamento por ascender sobre as pessoas"],
      behaviors: ["Exige admiração excessiva", "Falta de empatia"],
      deficits: ["Sensibilidade Social", "Reciprocidade"],
      newSkills: ["Reciprocidade", "Humildade Estratégica"],
      schemes: ["Arrogo/Grandiosidade", "Busca de Aprovação"],
      coreBeliefs: ["Sou superior", "Sou vulnerável à mediocridade"],
      peripheralBeliefs: ["As leis normais não se aplicam a mim"]
    },
    { 
      name: "Personalidade Evitativa",
      functionalName: "Transtorno de Evitação da Punição Social",
      desc: "Inibição social e hipersensibilidade a críticas.",
      history: ["Privação de oportunidades sociais", "Bullying"],
      cognitions: ["Sou feio, desajeitado, indesejável"],
      maintaining: ["Reforçamento negativo pela fuga da rejeição"],
      behaviors: ["Evita atividades interpessoais", "Relutância em se envolver"],
      deficits: ["Autoestima", "Habilidades Sociais"],
      newSkills: ["Exposição Gradual", "Habilidades de Conversação"],
      schemes: ["Defectividade/Vergonha", "Isolamento Social"],
      coreBeliefs: ["Sou inadequado", "Sou rejeitável"],
      peripheralBeliefs: ["Se eu me esconder, não serei ferido"]
    },
    { 
      name: "Personalidade Paranóide",
      functionalName: "Transtorno de Evitação da Exploração Social",
      desc: "Desconfiança e suspeitas pervasivas em relação aos outros.",
      history: ["Histórico de humilhação por cuidadores"],
      cognitions: ["As pessoas abusam e maltratam"],
      maintaining: ["Reforçamento negativo pela fuga de abusos"],
      behaviors: ["Suspeitas sem fundamento", "Guarda rancor"],
      deficits: ["Raciocínio Realisticamente Otimista", "Sensibilidade Social"],
      newSkills: ["Verificação de Evidências", "Confiança Gradual"],
      schemes: ["Desconfiança/Abuso"],
      coreBeliefs: ["O mundo é hostil", "As pessoas são perversas"],
      peripheralBeliefs: ["Devo estar sempre alerta para o ataque"]
    },
    { 
      name: "Personalidade Passivo-Agressiva",
      functionalName: "Transtorno de Evitação de Subjugação",
      desc: "Resistência passiva a demandas sociais e laborais.",
      history: ["Relações autoritárias com regras ilógicas"],
      cognitions: ["Ninguém manda em mim", "Não aceito ser dominado"],
      maintaining: ["Reforçamento negativo pela fuga do controle autoritário"],
      behaviors: ["Sarcasmo", "Atrasos propositais", "Ineficiência"],
      deficits: ["Assertividade", "Sensibilidade Social"],
      newSkills: ["Assertividade Direta", "Colaboração Eficaz"],
      schemes: ["Subjugação", "Padrões Inflexíveis"],
      coreBeliefs: ["Sou controlado", "Poder é perigoso"],
      peripheralBeliefs: ["Se eu disser não diretamente, serei punido; melhor sabotar"]
    },
    { 
      name: "Personalidade Esquizóide",
      functionalName: "Transtorno de Evitação da Reciprocidade Social",
      desc: "Distanciamento social e restrição da expressão emocional.",
      history: ["Relações sem afeto", "Déficit de reforçamento social"],
      cognitions: ["Prefiro viver sozinho", "Relacionamentos são confusos"],
      maintaining: ["Reforçamento negativo pela fuga da demanda social"],
      behaviors: ["Escolhe atividades solitárias", "Indiferente a elogios"],
      deficits: ["Sociabilidade", "Sensibilidade Social"],
      newSkills: ["Abertura Social", "Compartilhamento Emocional"],
      schemes: ["Isolamento Social", "Privação Emocional"],
      coreBeliefs: ["Sou diferente", "O mundo é barulhento"],
      peripheralBeliefs: ["Estar só é o único jeito de ter paz"]
    },
    { 
      name: "Personalidade Esquizotípica",
      functionalName: "Transtorno de Evitação da Normatização Social Coercitiva",
      desc: "Distorções cognitivas, excentricidades e desconforto social.",
      history: ["Histórico de bullying por ser diferente"],
      cognitions: ["As pessoas não aceitam o diferente"],
      maintaining: ["Reforçamento pela fuga de humilhações"],
      behaviors: ["Crenças estranhas", "Aparência excêntrica"],
      deficits: ["Acurácia perceptiva", "Sociabilidade"],
      newSkills: ["Funcionalidade Social", "Pensamento Realista"],
      schemes: ["Isolamento Social", "Desconfiança/Abuso"],
      coreBeliefs: ["Sou estranho", "Tenho poderes ou insights únicos"],
      peripheralBeliefs: ["Devo me proteger da incompreensão alheia"]
    },
    { 
      name: "Personalidade Borderline",
      functionalName: "Transtorno por Hipermobilização de Reforçamento Social sob Múltiplas Operações Estabelecedoras",
      desc: "Instabilidade nos afetos, impulsividade e autoimagem.",
      history: ["Histórico de perdas, abandono e invalidação"],
      cognitions: ["Sou uma pessoa vazia e carente"],
      maintaining: ["Reforçamento social múltiplo: atenção, cuidado"],
      behaviors: ["Instabilidade afetiva", "Impulsividade", "Relacionamentos caóticos"],
      deficits: ["Autorregulação Emocional", "Eficácia Interpessoal"],
      newSkills: ["Eficácia Interpessoal", "Tolerância ao Mal-estar"],
      schemes: ["Abandono/Instabilidade", "Privação Emocional", "Defectividade"],
      coreBeliefs: ["Sou indesejável", "Serei abandonado", "Sou mau"],
      peripheralBeliefs: ["Se eu não for extremo, as pessoas vão me deixar"]
    },
    { 
      name: "Personalidade Dependente",
      functionalName: "Transtorno da Mediação de Reforçamento",
      desc: "Necessidade excessiva de ser cuidado, submissão.",
      history: ["Superproteção e mediação constante"],
      cognitions: ["Não consigo viver sozinho", "Preciso de ajuda para decidir"],
      maintaining: ["Reforçamento em preservar fontes de proteção"],
      behaviors: ["Dificuldade em tomar decisões", "Medo da separação"],
      deficits: ["Autonomia", "Assertividade"],
      newSkills: ["Autodeterminação", "Independência Prática"],
      schemes: ["Dependência/Incompetência", "Emaranhamento"],
      coreBeliefs: ["Sou incapaz", "Preciso de alguém forte"],
      peripheralBeliefs: ["Se eu não agradar, serei abandonado e morrerei"]
    },
    { 
      name: "Transtornos Somatoformes (Psicossomáticos)",
      functionalName: "Transtorno dos Subprodutos Emocionais Lesivos sob Coerções",
      desc: "Presença de sintomas físicos sem explicação médica total.",
      history: ["Histórico de inescapabilidade de estimulação aversiva"],
      cognitions: ["Sou frágil e vulnerável"],
      maintaining: ["Reforçamento social pelas doenças", "Reforço negativo pela fuga de tarefas"],
      behaviors: ["Queixas em diversos sistemas (circulatório, digestivo)"],
      deficits: ["Autorregulação Emocional", "Resolutividade"],
      newSkills: ["Somatização Saudável", "Comunicação Assertiva"],
      schemes: ["Vulnerabilidade ao Dano", "Auto-sacrifício", "Dependência"],
      coreBeliefs: ["Eu não aguento a pressão", "Meu corpo está falhando"],
      peripheralBeliefs: ["Se eu estiver doente, eles param de me exigir"]
    },
    { 
      name: "Esquizofrenia",
      functionalName: "Transtorno da Evocação Privada de Reforçadores Simbólicos Exteroceptivamente Indissociados sob Desamparo",
      desc: "Distorções perceptivas, delírios e fala desorganizada.",
      history: ["Múltiplas privações e coerções severas"],
      cognitions: ["Estou ficando louco", "Não tenho controle"],
      maintaining: ["Reforçamento positivo in equivalência", "Fuga de estímulos"],
      behaviors: ["Delírios", "Alucinações", "Discurso desorganizado"],
      deficits: ["Monitoramento da Realidade", "Habilidades Sociais"],
      newSkills: ["Monitoramento da Realidade", "Gestão de Alucinações"],
      schemes: ["Isolamento Social", "Desconfiança/Abuso", "Defectividade"],
      coreBeliefs: ["O mundo é aterrorizante", "Eu sou um estranho"],
      peripheralBeliefs: ["Só na minha mente estou seguro"]
    },
    { 
      name: "Transtorno Dissociativo de Identidade",
      functionalName: "Transtorno de Múltiplos Repertórios Pareados com Distintas Regras Identitárias Evocados sob Efeito da Estimulação Discriminativa ou Desamparo",
      desc: "Presença de duas ou mais identidades distintas.",
      history: ["Histórico de desamparo generalizado e traumas severos"],
      cognitions: ["Meu corpo não me pertence", "Estou confuso"],
      maintaining: ["Reforçamentos múltiplos por alternância de papéis"],
      behaviors: ["Descontinuidade da consciência e memória"],
      deficits: ["Integração de Identidade", "Autorregulação"],
      newSkills: ["Integração de Identidade", "Foco no Agora"],
      schemes: ["Abandono/Instabilidade", "Desconfiança/Abuso", "Emaranhamento"],
      coreBeliefs: ["Eu estou fragmentado", "Eu não sou seguro"],
      peripheralBeliefs: ["Se eu mudar de 'quem eu sou', a dor para"]
    }
  ],
  EstilosParentais: [
    { name: "Negligente", desc: "Baixo afeto e baixo limite; pais ausentes ou focados apenas nos próprios desejos." },
    { name: "Autoritário", desc: "Baixo afeto e alto controle; foco em obediência cega e punição." },
    { name: "Permissivo", desc: "Alto afeto e baixo limite; a criança manda na casa e não aprende regras." },
    { name: "Superprotetor", desc: "Alto afeto e alto controle; impede a autonomia por medo de danos à criança." },
    { name: "Democrático / Responsivo", desc: "Equilíbrio entre afeto e limites; regras são explicadas e sentimentos ouvidos." }
  ],
  RID_Contextos: [
    { name: "Trabalho / Reunião", desc: "Ambiente profissional sob pressão ou avaliação." },
    { name: "Interação Social", desc: "Festas, conversas casuais ou encontro com estranhos." },
    { name: "Momento de Solidão", desc: "Em casa, à noite, ou durante o ócio." },
    { name: "Conflito Familiar", desc: "Discussões com parceiros, pais ou filhos." },
    { name: "Desafio Acadêmico", desc: "Provas, estudos ou apresentações." }
  ],
  RID_Pensamentos: [
    { name: "Pensamento Catastrófico", desc: "Esperar sempre pelo pior cenário possível." },
    { name: "Leitura Mental", desc: "Achar que sabe o que os outros estão pensando de forma negativa." },
    { name: "Raciocínio Emocional", desc: "Achar que porque sente algo, aquilo é uma verdade absoluta." },
    { name: "Tudo ou Nada", desc: "Visão binária da vida; se não for perfeito, é um fracasso total." },
    { name: "Personalização", desc: "Atribuir a si mesmo a culpa por eventos externos fora de seu controle." }
  ],
  RID_Emocoes: [
    { name: "Ansiedade / Medo", desc: "Sensação de perigo iminente ou apreensão." },
    { name: "Tristeza / Desânimo", desc: "Sentimento de perda ou falta de energia vital." },
    { name: "Raiva / Irritabilidade", desc: "Resposta a injustiças percebidas ou bloqueio de metas." },
    { name: "Culpa / Vergonha", desc: "Sentimento de ter violado regras próprias ou ser inadequado." },
    { name: "Vazio Emocional", desc: "Sensação de anestesia ou falta de sentido." }
  ],
  RID_Comportamentos: [
    { name: "Esquiva Comportamental", desc: "Fugir ou evitar fisicamente a situação temida." },
    { name: "Procrastinação", desc: "Adiar tarefas para não lidar com o desconforto que elas geram." },
    { name: "Busca de Reasseguramento", desc: "Perguntar constantemente se está tudo bem ou se agiu certo." },
    { name: "Isolamento Social", desc: "Afastar-se das pessoas para se proteger." },
    { name: "Compensação / Perfecionismo", desc: "Trabalhar em excesso para tentar esconder falhas percebidas." }
  ],
  RID_ConsequenciasCP: [
    { name: "Alívio Imediato", desc: "Redução rápida da ansiedade ou desconforto após a esquiva." },
    { name: "Reforçamento Social", desc: "Ganho de atenção ou cuidado através da expressão do sofrimento." },
    { name: "Aumento do Medo", desc: "Sensação de que o perigo foi evitado por sorte desta vez." }
  ],
  RID_ConsequenciasLP: [
    { name: "Manutenção do Sintoma", desc: "O problem persiste porque o paciente nunca o enfrenta de fato." },
    { name: "Perda de Oportunidades", desc: "Prejuízos na carreira, estudos ou relacionamentos por conta da evitação." },
    { name: "Queda na Autoestima", desc: "Sentimento de ser incapaz de lidar com as dificuldades da vida." }
  ],
  HabilidadesPsicologicas: [
    { name: "Autorregulação Emocional", desc: "Capacidade de lidar com emoções intensas sem agir por impulso." },
    { name: "Assertividade", desc: "Expressar necessidades e limites de forma clara e respeitosa." },
    { name: "Resolução de Problemas", desc: "Habilidade de quebrar desafios em passos executáveis." },
    { name: "Flexibilidade Cognitiva", desc: "Capacidade de ver situações sob diferentes perspectivas." },
    { name: "Autonomia", desc: "Capacidade de tomar decisões e agir de forma independente." }
  ],
  Excessos_Comportamentais: [
    { name: "Ruminação Cognitiva", desc: "Ciclo repetitivo de pensamentos negativos sobre o passado ou problemas presentes sem foco na solução." },
    { name: "Hipervigilância Ambiental", desc: "Estado de alerta constante para possíveis perigos ou sinais de rejeição no ambiente." },
    { name: "Perfeccionismo Paralisante", desc: "Busca por padrões impossíveis que impedem a finalização de tarefas simples." },
    { name: "Verborragia Defensiva", desc: "Falar excessivamente para evitar silêncios desconfortáveis ou para dominar a narrativa social." },
    { name: "Busca Obsessiva de Aprovação", desc: "Pedir validação para cada escolha, desde roupas até decisões de carreira." },
    { name: "Consumo Impulsivo (Binge)", desc: "Gasto, comida, redes sociais ou jogos como forma de anestesia emocional." },
    { name: "Workaholismo", desc: "Uso do trabalho excessivo como fuga de responsabilidades emocionais ou conflitos familiares." },
    { name: "Reclamação Crônica", desc: "Focar exclusivamente em obstáculos, reforçando o papel de vítima e o desamparo." },
    { name: "Controle Interpessoal", desc: "Tentar gerenciar cada ação das pessoas próximas para reduzir a própria ansiedade." },
    { name: "Procrastinação Ativa", desc: "Ocupar-se com micro-tarefas irrelevantes para fugir do desafio principal que gera medo." },
    { name: "Agressividade Passiva", desc: "Expressar raiva através de atrasos, esquecimentos ou sarcasmo em vez de diálogo." }
  ],
  Diagnostico_Funcional: [
    { name: "Esquiva Experiencial", desc: "Incapacidade de estar em contato com sentimentos ruins, levando ao uso de comportamentos que geram alívio imediato mas mantêm o problema." },
    { name: "Reforço Negativo (Alívio)", desc: "O comportamento disfuncional é mantido porque retira um estímulo aversivo (dor, medo, culpa) no curto prazo." },
    { name: "Baixa Variabilidade Comportamental", desc: "Repetição rígida dos mesmos padrões de resposta, independentemente de estarem funcionando ou não na situação atual." },
    { name: "Reforço Positivo (Curto Prazo)", desc: "O padrão é mantido pelo recebimento de prazer, atenção ou status imediato, ignorando consequências futuras." },
    { name: "Punição Contingente", desc: "O ambiente pune as tentativas de mudança do paciente, forçando-o de volta ao padrão anterior." },
    { name: "Desamparo Aprendido", desc: "Histórico onde as ações do indivíduo não mudavam o ambiente ruim, gerando passividade e falta de iniciativa atual." },
    { name: "Déficit de Repertório", desc: "O paciente não tem o comportamento saudável 'na caixa de ferramentas'; ele nunca aprendeu a agir de forma diferente." },
    { name: "Controle por Regras Rígidas", desc: "O comportamento é guiado por 'deveria' verbais históricos em vez das consequências naturais do ambiente presente." },
    { name: "Fusão Cognitiva", desc: "O paciente age como se seus pensamentos fossem fatos literais e perigosos." },
    { name: "Insensibilidade às Contingências", desc: "Dificuldade em perceber que o ambiente mudou e que as estratégias antigas de sobrevivência não são mais necessárias." }
  ],
  Projeto_Terapeutico: [
    { name: "Reabilitação Esquematica", desc: "Foco em enfraquecer esquemas através de reestruturação cognitiva e experimentos comportamentais de enfrentamento." },
    { name: "Treino de Habilidades (THS)", desc: "Desenvolvimento explícito de habilidades deficitárias (assertividade, comunicação, resolução de problemas) em sessão." },
    { name: "Prevenção de Recaída", desc: "Identificação de situações de risco e criação de um plano de ação para lapsos." },
    { name: "Reparentalização Limitada", desc: "O terapeuta atua dentro dos limites éticos para suprir necessidades infantis não atendidas." },
    { name: "Exposição com Prevenção de Resposta (ERP)", desc: "Quebrar o ciclo de esquiva expondo o paciente ao medo e impedindo o comportamento de segurança." },
    { name: "Ativação Comportamental", desc: "Aumento gradual de atividades que geram prazer e domínio." },
    { name: "Estabelecimento de Valores", desc: "Mudar o foco do 'não sofrimento' para a construção de uma vida com sentido e propósito." }
  ],
  Historico_Formativo: [
    { name: "Superproteção Asfixiante", desc: "Ambiente onde a criança foi impedida de cair, errar ou decidir." },
    { name: "Rejeição e Desprezo", desc: "Histórico de ser humilhado, ridicularizado ou explicitamente rejeitado." },
    { name: "Abuso Físico/Psicológico", desc: "Sofrimento de traumas deliberados que geraram uma visão do mundo como um lugar onde as pessoas ferem." },
    { name: "Parentalização Precoce", desc: "Inversão de papéis onde a criança teve que ser o suporte emocional ou prático." },
    { name: "Clima de Crítica Punitiva", desc: "Ambiente onde o erro era inaceitável e a punição era o principal método." },
    { name: "Instabilidade e Caos Familiar", desc: "Histórico de mudanças bruscas, brigas constantes ou divórcio traumático." },
    { name: "Privação de Afeto e Validação", desc: "Necessidade emocionais ignoradas; a criança nunca era ouvida." },
    { name: "Bullying e Exclusão por Pares", desc: "Traumas sociais na escola que consolidaram esquemas." },
    { name: "Exigência de Sucesso a Qualquer Custo", desc: "Pais que condicionavam o amor ao desempenho perfeito." },
    { name: "Herança Intergeracional de Medo", desc: "Pais que projetavam suas próprias fobias na criança." }
  ],
  NovasFuncoes: [
    { name: "Atenção Plena (Mindfulness)", desc: "Estar presente no momento atual sem julgamento." },
    { name: "Aceitação Radical", desc: "Aceitar a realidade como ela é, reduzindo o sofrimento." },
    { name: "Eficácia Interpessoal", desc: "Habilidade de conseguir o que se quer mantendo o autorrespeito." },
    { name: "Tolerância ao Mal-estar", desc: "Capacidade de sobreviver a crises sem agir de forma impetuosa." },
    { name: "Exposição com Prevenção de Resposta (ERP)", desc: "Contato com o estímulo temido sem realizar o ritual habitual." },
    { name: "Reestruturação Cognitiva", desc: "Substituir pensamentos distorcidos por visões realistas." },
    { name: "Ativação Comportamental", desc: "Engajamento planejado em atividades que promovem prazer." },
    { name: "Auto-validação", desc: "Reconhecer a própria experiência emocional como legítima." },
    { name: "Treino de Assertividade", desc: "Aprender a expressar opiniões de forma firme e respeitosa." },
    { name: "Higiene do Sono / Organização", desc: "Criação de rotinas estruturadas favoráveis à saúde." }
  ],
  QueixasComuns: [
    { name: "Ansiedade de Desempenho", desc: "Ansiedade intensa diante de avaliações, reuniões ou apresentações em público, com taquicardia e sudorese." },
    { name: "Desânimo e Falta de Sentido", desc: "Tristeza persistente, apatia em relação a hobbies, sentimentos de incompetência e isolamento social." },
    { name: "Dificuldades Interpessoais (Família)", desc: "Conflitos conjugais ou familiares frequentes, com dificuldades de comunicação assertiva e sentimentos de invalidação." },
    { name: "Procrastinação e Perfeccionismo", desc: "Atraso no início de tarefas importantes por medo de falhar, gerando ciclos de culpa e ansiedade." },
    { name: "Crises de Pânico", desc: "Episódios súbitos de medo intenso com palpitações, falta de ar e medo de morrer ou enlouquecer." }
  ],
  RotinasComuns: [
    { name: "Home Office Sedentário", desc: "Trabalho remoto, privação de sono (menos de 6h/noite), sem atividades físicas regulares, alto consumo de telas." },
    { name: "Estudante sob Estresse", desc: "Rotina irregular de estudos, consumo elevado de cafeína, sem horários fixos para alimentação, pouca exposição solar." },
    { name: "Jornada Exaustiva", desc: "Trabalho presencial acima de 44h semanais, pouco tempo livre para lazer, exaustão mental e sono fragmentado." }
  ],
  InstrumentosComuns: [
    { name: "Inventário de Habilidades Psicológicas (IHP-PR)", desc: "Mapeamento de autoconhecimento, autoestima, autorregulação e sociabilidade." },
    { name: "Questionário de Esquemas de Young (YSQ-S3)", desc: "Identificação de esquemas iniciais desadaptativos e domínios esquemáticos." },
    { name: "Registro de Identificação de Disfunções (RID)", desc: "Análise funcional contextualizada de pensamentos, emoções e comportamentos." },
    { name: "Inventário de Satisfação (IMF)", desc: "Avaliação do nível de satisfação nas áreas pessoal, interpessoal, ocupacional, material, recreativa e existencial." },
    { name: "Inventários de Depressão/Ansiedade de Beck (BDI/BAI)", desc: "Instrumentos clínicos estruturados para mensuração de gravidade de sintomas." }
  ],
  RelacionamentoTerapComuns: [
    { name: "Empirismo Colaborativo", desc: "Terapeuta e paciente atuam como cientistas parceiros, testando hipóteses sobre os pensamentos e comportamentos." },
    { name: "Reparentalização Limitada", desc: "O terapeuta busca suprir, dentro dos limites éticos, necessidades infantis não atendidas na história formativa." },
    { name: "Confrontação Empática", desc: "Apontar de forma respeitosa e afetuosa as inconsistências entre os objetivos saudáveis do paciente e seus comportamentos de esquiva." },
    { name: "Acolhimento e Validação", desc: "Foco em validar as emoções difíceis do paciente, oferecendo um porto seguro e reduzindo a autocrítica." },
    { name: "Postura Firme e Limites", desc: "Estabelecimento de limites interpessoais claros e previsíveis para pacientes com esquemas de direito ou grandiosidade." }
  ],
  EvolucoesComuns: [
    { name: "Adesão e Aliança", desc: "Paciente demonstrou boa aliança terapêutica, compreendeu a proposta do plano de conduta e engajou-se nas atividades." },
    { name: "Reestruturação Cognitiva", desc: "Sessão focada na identificação e questionamento de distorções cognitivas nos pensamentos automáticos." },
    { name: "Exposição e Enfrentamento", desc: "Paciente iniciou experimentos comportamentais de exposição gradual às situações temidas." },
    { name: "Prevenção de Recaída e Alta", desc: "Paciente apresenta estabilização dos sintomas, início da fase de prevenção de recaída e planejamento de alta progressiva." }
  ]
};
