import { Tool, ToolCategory } from "./types";

export const CATEGORIES: { id: ToolCategory; label: string; description: string; color: string }[] = [
  {
    id: "felicidade",
    label: "Felicidade",
    description: "Balanço afetivo, fontes de gratificação genuína e nível de satisfação multidimensional.",
    color: "from-pink-500 to-amber-500"
  },
  {
    id: "autoconhecimento",
    label: "Autoconhecimento",
    description: "Análise sistêmica, mapeamento cronológico-biográfico e exame de feedbacks e atributos pessoais.",
    color: "from-blue-500 to-indigo-700"
  },
  {
    id: "autoestima",
    label: "Autoestima",
    description: "Reconciliação e desenvolvimento da imagem pessoal, autoconceito e imersão em valores ativos.",
    color: "from-purple-500 to-pink-600"
  },
  {
    id: "racio_real_otimista",
    label: "Raciocínio Realistamente Otimista",
    description: "Combate de visões catastróficas, reestruturação semântica e do balanço fático de evidências.",
    color: "from-cyan-500 to-teal-605"
  },
  {
    id: "resolut_enfrent",
    label: "Resolutividade e Enfrentamento",
    description: "Hierarquização de estressores, cartões de enfrentamento estruturados e planos de exposição gradual.",
    color: "from-emerald-500 to-teal-700"
  },
  {
    id: "imunidade_social",
    label: "Imunidade Social",
    description: "Fortalecimento da autonomia pessoal frente a críticas, rótulos e interferências do ambiente.",
    color: "from-violet-600 to-fuchsia-600"
  },
  {
    id: "autocontrole",
    label: "Autocontrole",
    description: "Planejamento focado, disciplina ativa, tomada de decisões estruturadas e monitoramento de metas vitais.",
    color: "from-amber-500 to-orange-700"
  },
  {
    id: "mentalidades",
    label: "Mentalidades Saudáveis",
    description: "Conjunto complementar de âncoras cognitivas para regulação comportamental continuada em múltiplas HPs.",
    color: "from-rose-500 to-rose-700"
  }
];

export const INITIAL_TOOLS: Tool[] = [
  {
    id: "satisfacao_multidimensional",
    code: "F1",
    title: "Análise da Satisfação Multidimensional (Felicidade - T2)",
    description: "Mapeia o nível de bem-estar corporal, social, laboral e interior do paciente em 6 dimensões vitais: pessoal, interpessoal, ocupacional, material, recreativa e existencial. Organiza as fontes correntes de felicidade/gratificação (recursos) e identifica o que está pendente (metas terapêuticas/coaching), calculando o Índice de Satisfação Geral (ISG).",
    category: "felicidade",
    duration: "10 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Qualidade de Vida", "Satisfação Existencial", "Delineamento de Metas", "Autocuidado Ativo", "Autoconhecimento Prático"],
    status: "ready",
    icon: "Target",
    scoringInfo: "Calcula o Índice de Satisfação Geral (ISG), mensurando em percentual e dividindo o equilíbrio de investimentos vitais entre cada uma das 6 dimensões."
  },
  {
    id: "avaliacao_central",
    code: "F2",
    title: "Avaliação Central (Autoconhecimento - T32)",
    description: "Formulação clínica integrada: mapeia contingências disfuncionais, forças de assinatura, esquemas desadaptativos, necessidades, habilidades psicológicas e contingências curativas.",
    category: "autoconhecimento",
    duration: "15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Esquemas Desadaptativos", "Contingências Curativas", "Habilidades Psicológicas", "Forças de Assinatura"],
    status: "ready",
    icon: "ClipboardCheck",
    scoringInfo: "Calcula o Índice de Funcionamento Adaptativo (IFA) sintetizando forças, HPs e contingências curativas sobre estressores e esquemas e orientando soluções."
  },
  {
    id: "genealogia_atributos",
    code: "F3",
    title: "Genealogia dos Atributos Pessoais (Autoconhecimento - T35)",
    description: "Análise sistêmica e genograma de forças e fraquezas herdadas transgeracionalmente, promovendo a HP de autoconhecimento e a identificação de heranças comportamentais.",
    category: "autoconhecimento",
    duration: "10 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoconhecimento", "Herança Comportamental", "Sistêmica Familiar", "Delineamento de Recursos"],
    status: "ready",
    icon: "Users",
    scoringInfo: "Calcula o Índice de Integração Transgeracional (IIT) avaliando a consciência de virtudes herdadas, aceitação de vulnerabilidades e coerência estrutural da linhagem."
  },
  {
    id: "linha_vida",
    code: "F4",
    title: "Linha da Vida (Autoconhecimento - T37)",
    description: "Mapeamento cronológico-biográfico de experiências significativas. Registra idades em círculos e direciona vetores para cima (experiências construtivas/recursos) ou para baixo (adversidades/sofrimento de aprendizado), promovendo a HP de autoconhecimento histórico.",
    category: "autoconhecimento",
    duration: "10 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoconhecimento", "Histórico Biográfico", "Processamento de Adversidades", "Integração de Recursos"],
    status: "ready",
    icon: "Clock",
    scoringInfo: "Mapeia o equilíbrio resiliência/adversidade, a amplitude de autoexploração e o Índice de Conexão Biométrica (ICB) através da integração integrativa de vivências."
  },
  {
    id: "radar_multidimensional",
    code: "F5",
    title: "Radar Multidimensional (Autoconhecimento - T39)",
    description: "Diagrama polar interativo de 18 subescalas que avalia o equilíbrio vital do paciente através dos setores físico, relacional, ocupacional, material, de lazer e existencial. Calibre diretamente no gráfico para mapear forças e recessões.",
    category: "autoconhecimento",
    duration: "12 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Equilíbrio Vital", "Diagrama Radial", "Mapeamento Multidimensional", "Calibragem Direta", "Autoconhecimento Sistêmico"],
    status: "ready",
    icon: "Sliders",
    scoringInfo: "Calcula o Índice de Funcionamento Radial (IFR) integrando o preenchimento de todas as 18 sub-esferas vitais e dividindo por dimensão principal."
  },
  {
    id: "radar_habilidades",
    code: "F6",
    title: "Radar de Habilidades Psicológicas (Autoconhecimento - T41)",
    description: "Mapeamento polar interativo de 10 habilidades psicológicas chave do método THP: Autoconhecimento, Autoestima, Racionalidade, Regulação Emocional, Enfrentamento, Imunidade Social, Autocontrole, Sociabilidade, Sensibilidade e Hedonismo. Calibre cada fatia de 1 a 10.",
    category: "autoconhecimento",
    duration: "10 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Mapeamento de HPs", "Autoconhecimento", "Autoestima", "Metacognição Ativa", "Equilíbrio Comportamental"],
    status: "ready",
    icon: "Activity",
    scoringInfo: "Calcula o Índice de Amplitude das Habilidades (IAH) integrando a pontuação auto-relatada de 1 a 10 de cada uma das 10 habilidades."
  },
  {
    id: "exame_feedbacks",
    code: "F7",
    title: "Exame de Feedbacks - Rótulos (Autoconhecimento - T41)",
    description: "Mapeia os comportamentos e traços interpessoais mais marcantes do paciente sob a ótica de múltiplos observadores (familiares, cônjuges, parceiros de trabalho) comparados à sua autopercepção. Avalia 31 rótulos comportamentais frequentes e calcula o Índice de Alinhamento Perceptivo (IAP) para guiar o autoconhecimento sociointeracional consciente.",
    category: "autoconhecimento",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Alinhamento Perceptivo", "Metacognição Interpessoal", "Comunicação Construtiva", "Pontos Cegos Sociais", "Diferenciação Emocional"],
    status: "ready",
    icon: "Users",
    scoringInfo: "Calcula o Índice de Alinhamento Perceptivo (IAP), o Índice de Virtudes de Convivência (IVC), e mapeia pontos cegos de autoridade ou passividade recorrentes."
  },
  {
    id: "exame_feedbacks_entrevista",
    code: "F8",
    title: "Exame de Feedbacks - Entrevista e Filtros (Autoconhecimento - T43)",
    description: "Método de entrevista estruturada para coletar e analisar feedbacks sinceros de pessoas próximas do convívio do paciente (cônjuge, filho, amigo). Desenvolve as HPs de Autoestima, Autoconhecimento e Imunidade Social ao filtrar as percepções alheias sob as lentes da Ética e da Ciência (verificabilidade, justiça conceitual, verdade factual e princípios de respeito).",
    category: "autoconhecimento",
    duration: "15-20 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoestima", "HP de Autoconhecimento", "HP de Imunidade Social", "Filtro Científico", "Filtro Ético", "Diferenciação do Self"],
    status: "ready",
    icon: "MessageSquare",
    scoringInfo: "Calcula o Índice de Racionalidade de Feedback (IRF) baseando-se na correspondência com a realidade, verificabilidade e alinhamento do relato a princípios éticos."
  },
  {
    id: "exame_atributos_pessoais",
    code: "F9",
    title: "Exame da Qualidade dos Atributos Pessoais (Autoconhecimento - T46)",
    description: "Mapeia e reconcilia o autoconceito do paciente através de quatro quadrantes decisivos de autoimagem e valores pessoais: 'Sou e gosto de ser', 'Sou e não gosto de ser', 'Não sou e gostaria de ser' e 'Não sou e gosto de não ser'. Permite formular com clareza os projetos de formação de novas HPs e consolidar a autoestima baseada em virtudes ativas e autoproteção frente a comportamentos deletérios alheios.",
    category: "autoconhecimento",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoestima", "HP de Autoconhecimento", "Autoaceitação Progressiva", "Projetos de Desenvolvimento", "Alinhamento de Valores", "Autoconsciência Crítica"],
    status: "ready",
    icon: "Fingerprint",
    scoringInfo: "Calcula o Índice de Satisfação Consciencial (ISC) e o Potencial de Desenvolvimento de HPs (PDH) baseando-se no balanceamento qualitativo dos quadrantes de autoimagem."
  },
  {
    id: "exame_singulares_compartilhadas",
    code: "F10",
    title: "Exame de Características Singulares e Compartilhadas (Autoconhecimento - T47)",
    description: "Analisa o autoconceito e consolida as HPs de Autoestima e Autoconhecimento ao discriminar características de personalidade sob duas categorias ecológicas: Singulares (traços particulares, raros ou específicos do sujeito) e Compartilhadas (habilidades e valores comuns, socialmente validados). Desenvolve o senso saudável de exclusividade individual combinado ao pertencimento comunitário.",
    category: "autoconhecimento",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoestima", "HP de Autoconhecimento", "Exclusividade de Repertório", "Pertencimento Social", "Integração do Autoconceito", "Apreço de Virtudes"],
    status: "ready",
    icon: "Fingerprint",
    scoringInfo: "Calcula o Índice de Exclusividade Identitária (IEI) e o Índice de Pertencimento Compartilhado (IPC), medindo a harmonia no desenho da autoimagem."
  },
  {
    id: "exame_atributos_parentais",
    code: "F11",
    title: "Exame dos Atributos Parentais (Autoconhecimento - T48)",
    description: "Mapeamento clínico sistemático de 52 características predominantes dos cuidadores principais do paciente. Permite a avaliação paralela e comparativa de múltiplos cuidadores (por exemplo, pai, mãe, avós), investigando o Índice de Nutrição Parental (INP) e o Índice de Estressores Parentais (ISP), correlacionando-os de forma preditiva com Esquemas Iniciais Desadaptativos (EIDs) em potencial.",
    category: "autoconhecimento",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Esquemas Parentais", "Herança de Padrões", "Autoconhecimento Histórico", "Consciência Transgeracional", "Vínculos Primitivos"],
    status: "ready",
    icon: "Users",
    scoringInfo: "Calcula o Índice de Nutrição Parental (INP) e o Índice de Estressores Parentais (ISP) individuais por figura parental, rastreando vulnerabilidades para EIDs de abandono, padrões inflexíveis, desconfiança e subjugação."
  },
  {
    id: "exame_provisao_emocional",
    code: "F12",
    title: "Exame Histórico da Provisão Emocional (Autoconhecimento - T51)",
    description: "Mapeamento sistemático da frequência de 23 sentimentos fundamentais e formas de provimento afetivo vivenciados nos relacionamentos ao longo do desenvolvimento do paciente. Avalia carências esquemáticas históricas e apoia o delineamento de atitudes interpessoais maduras no presente para reparar lacunas de afeto, validação e conexões seguras.",
    category: "autoconhecimento",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoconhecimento", "Afeto e Validação", "Conexão Segura", "Reparação Esquemática", "Autossuficiência Consciencial"],
    status: "ready",
    icon: "Heart",
    scoringInfo: "Calcula o Índice de Provisão Emocional Global (IPEG), o Subíndice de Aceitação e Conexão (SAC) e o Subíndice de Autonomia e Valorização (SAV), auxiliando no direcionamento de vínculos reparadores."
  },
  {
    id: "exame_atitudes_dimensoes",
    code: "F13",
    title: "Exame das Atitudes e Efeitos nas Dimensões (Autoconhecimento - T52)",
    description: "Avalia sistematicamente o alinhamento existencial do paciente analisando três vetores cruciais ('O que sou', 'O que faço' e 'O que tenho') distribuídos de forma matricial em seis dimensões vitais: Pessoal, Interpessoal, Ocupacional, Material, Recreativa e Existencial. Útil para reestruturar congruência de identidade com as ações e conquistas reais.",
    category: "autoconhecimento",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoconhecimento", "Alinhamento Existencial", "Coerência de Identidade", "Ação Autogovernada", "Mapeamento Multidimensional", "Evolução do Self"],
    status: "ready",
    icon: "Layers",
    scoringInfo: "Mede o Índice de Congruência Identitária (ICI) e o Coeficiente de Produtividade Existencial (CPE) através da proporção e preenchimento dos eixos matriciais."
  },
  {
    id: "exame_reacoes_sociais",
    code: "F14",
    title: "Exame das Reações Sociais aos Meus Comportamentos (Autoconhecimento - T53)",
    description: "Espelho sociométrico e comportamental que ajuda o paciente a registrar, catalogar e conscientizar-se dos efeitos que seus próprios padrões de comportamento ativam nas pessoas au seu redor. Permite analisar múltiplas esferas (conjugal, profissional, familiar, social) para identificar padrões de autoafirmação e gatilhos de conflitos.",
    category: "autoconhecimento",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autoconhecimento", "Inteligência Interpessoal", "Sensibilidade Sociométrica", "Assertividade e Limites", "Padrões Comportamentais", "Regulação de Vínculos"],
    status: "ready",
    icon: "Activity",
    scoringInfo: "Calcula a proporção de Reações Adaptativas vs. Desadaptativas recebidas e o Índice de Consciência de Impacto Social (ICIS) em múltiplos contextos relacionais."
  },
  {
    id: "exame_desenvolvimento_autoestima",
    code: "F15",
    title: "Exame e Desenvolvimento da Autoestima (Autoestima - T61)",
    description: "Técnica de reestruturação de autoimagem e planejamento de auto-investimento. Avalia o autoconceito do paciente dividido em cinco dimensões cruciais (Aparência Física/Estética, Competências, Estilo Interpessoal, Autonomia e Valores), registrando o estado atual de apreciação acadêmica e as metas ativas de aprimoramento individual.",
    category: "autoestima",
    duration: "12-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Auto-investimento", "Autoaceitação Progressiva", "Assertividade de Autoimagem", "Metas de Desenvolvimento", "Consolidação de Valores"],
    status: "ready",
    icon: "Heart",
    scoringInfo: "Calcula o Índice de Autoestima Global (IAG) e o Índice de Desenvolvimento Ativo (IDA), ponderando o nível de contentamento presente frente ao investimento em planos e metas futuras de crescimento pessoal."
  },
  {
    id: "analise_modelos_pessoais",
    code: "F16",
    title: "Análise dos Modelos Pessoais (Autoestima - T62 e T63)",
    description: "Ferramenta Integradora nº 28 baseada em modelagem comportamental e aprendizagem social. Auxilia o paciente a mapear seus Modelos Atuais (familiares, convivência) e Modelos Ideais (mentores, personalidades), discriminando forças, limitações e impactos em seus sentimentos e comportamentos para estruturar uma atualização consciente de repertório.",
    category: "autoestima",
    duration: "15-20 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Modelagem Comportamental", "Habilidade de Aprendizagem Social", "Discriminação Diagnóstica de Influências", "Imersão de Conduta", "Virtudes e Forças de Caráter"],
    status: "ready",
    icon: "Users",
    scoringInfo: "Mapeia o impacto emocional e comportamental estimulado por modelos inconscientes do passado e orienta a adoção ativa e intencional de forças a partir de novos modelos ideais."
  },
  {
    id: "rid_interacoes",
    code: "F17",
    title: "Registro de Interações Disfuncionais - RID (Autoestima - T64)",
    description: "Versão expandida do RDPD de Aaron Beck. Desenvolve o autopoliciamento e autoconhecimento profundo ao mapear a situação, a necessidade latente do paciente, estressores reais/distorcidos, cognições nucleares, reações emocionais, excessos e déficits de ações, e as consequências imediatas e de longo prazo (reforço e punição), sincronizados ao histórico de vida do cliente.",
    category: "autoestima",
    duration: "15-25 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Mapeamento de Contexto", "Análise de Necessidades", "Estressores Reais vs Distorcidos", "Identificação de Cognições", "Expressão de Emoções", "Autocontrole Behavioral", "Mapeamento das Consequências", "Nexo de Histórico de Vida"],
    status: "ready",
    icon: "Clipboard",
    scoringInfo: "Calcula o Índice de Completude de Autoconsciência (ICA) com base no preenchimento detalhado das colunas de contexto, ações e consequências e no nível de correlação dos comportamentos atuais com as experiências históricas formativas."
  },
  {
    id: "transicao_mecanismo",
    code: "F18",
    title: "Transição para Mecanismo Funcional (Autoestima - T65)",
    description: "Conduz o paciente na transição da psicopatologia para o repertório reflexivo saudável. Mapeia e confronta o Mecanismo Disfuncional (esquemas desregulados, pensamentos enviesados, fugas/evitações e suas desvantagens) diretamente com o Mecanismo Funcional (esquemas autorregulados, mentalidade realista, ações adaptativas, vantagens e resultados desejados).",
    category: "autoestima",
    duration: "15-20 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Mecanismos de Defesa", "Mentalidade Adaptativa", "Enfrentamento Saudável", "Balanço Decisório de Vantagens", "Metas de Aprendizado", "Resignificação de Regras"],
    status: "ready",
    icon: "RefreshCw",
    scoringInfo: "Calcula o Índice de Eficácia Transicional (IET) com base na robustez e clareza das alternativas saudáveis desenhadas à direita e no contraste analítico do balanço de vantagens das colunas."
  },
  {
    id: "exame_evidencias_cognicao",
    code: "F19",
    title: "Exame de Evidências da Cognição (Racio. Real. Otimista - T78)",
    description: "Técnica clássica de reestruturação cognitiva para treinar a flexibilidade de pensamentos e estruturar o raciocínio realisticamente otimista. Permite colocar pensamentos disfuncionais e crenças limitantes à prova através do exame de fatos e evidências reais a favor e contra, culminando na formulação de pensamentos alternativos saudáveis e balanceados.",
    category: "racio_real_otimista",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Racionalidade Avançada", "Raciocínio Realístico", "Flexibilidade Cognitiva", "Mapeamento de Distorções", "Metacognição Ativa"],
    status: "ready",
    icon: "BrainCircuit",
    scoringInfo: "Calcula o Índice de Flexibilidade Cognitiva (IFC) e o Balanço de Evidências (BE), avaliando o peso das evidências factuais contra em oposição à convicção subjetiva na crença limitante."
  },
  {
    id: "reestruturacao_semantica",
    code: "F20",
    title: "Reestruturação Semântica (Racio. Real. Otimista - T83)",
    description: "Técnica cognitivo-linguística para analisar as redes de significados de termos rígidos ou fóbicos (como 'ser racional', 'felicidade', 'prosperidade' ou 'ser forte'). Mapeia sinônimos errôneos (associados desadaptativos como 'ser frio' para 'racional') e opostos em colunas paralelas para reorganizar de forma flexível e realista as regras cognitivas do sujeito.",
    category: "racio_real_otimista",
    duration: "10-12 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Raciocínio Realístico", "Diferenciação Linguística", "Flexibilidade Cognitiva", "Mapeamento Semântico", "Análise de Regras Rígidas"],
    status: "ready",
    icon: "BookOpen",
    scoringInfo: "Calcula o Índice de Dissociação Semântica (IDS) e o Alinhamento Adaptativo, aferindo o nível de reelaboração conceitual saudável após a quebra de fusão cognitiva."
  },
  {
    id: "cartao_enfrentamento",
    code: "F21",
    title: "Cartão de Enfrentamento (Racio. Real. Otimista - T87)",
    description: "Técnica clássica de consolidação de raciocínios alternativos saudáveis. Estrutura cartões de bolso contendo a mentalidade disfuncional narrativa (crença e seus desdobramentos subjetivos) confrontada por uma mentalidade reestruturada (Raciocínio Realístico-Otimista). Valida cientificamente e eticamente as premissas objetivas para criar maior convicção e reduzir impulsos desadaptativos automatizados diante de disparadores situacionais desafiadores.",
    category: "racio_real_otimista",
    duration: "8-10 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Raciocínio Realístico", "Flexibilidade Cognitiva", "Auto-instrução Consolidada", "Controle Emocional", "Ação Baseada em Valores"],
    status: "ready",
    icon: "CreditCard",
    scoringInfo: "Calcula o Índice de Eficácia do Enfrentamento (IEE) com base nas validações éticas e científicas preenchidas, no mapeamento de distorções cognitivas e no nível de convicção subjetiva na reestruturação criada."
  },
  {
    id: "despolarizacao_alternativas",
    code: "F22",
    title: "Geração de Alternativas para Despolarização (Racio. Real. Otimista - T88)",
    description: "Técnica clínica de despolarização cognitiva (também chamada de Ponto-Contraponto). Auxilia o paciente a identificar raciocínios polarizados e extremistas (Polo Esquerdo e Polo Direito) e estruturar uma Alternativa Intermediária (ponto do meio) que reúne e acomode as melhores evidências factuais e os parâmetros éticos e de realidade de ambos os lados, restaurando a flexibilidade e o equilíbrio cognitivo.",
    category: "racio_real_otimista",
    duration: "8-12 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Flexibilidade Cognitiva", "Mapeamento de Extremos", "Raciocínio Integrativo", "Moderação Cognitiva", "Equilíbrio de Evidências"],
    status: "ready",
    icon: "Scale",
    scoringInfo: "Calcula o Índice de Moderação Cognitiva (IMC) com base no nível de extremismo reportado para cada polo, na amplitude de fatos objetivos integrados à alternativa intermediária, e no grau de convicção na conciliação integrada."
  },
  {
    id: "mapeamento_estressores",
    code: "F23",
    title: "Mapeamento de Estressores (Resolut. e Enfrent. - T126)",
    description: "Mapeia os estressores e pendências (imediatos, históricos, pequenos ou grandes) que sobrecarregam o paciente, classificando-os em Controláveis ou Incontroláveis e estruturando uma Hierarquia de Resolução para desenvolver a HP de resolutividade e enfrentamento ativo.",
    category: "resolut_enfrent",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Resolutividade de Problemas", "Enfrentamento Ativo", "Discriminação de Controle", "Organização Cognitiva", "Redução de Ansiedade"],
    status: "ready",
    icon: "Activity",
    scoringInfo: "Calcula o Índice de Controlabilidade dos Estressores (ICE) e o Índice de Resolutividade Prática (IRP), baseando-se no planejamento hierárquico e discernimento do paciente."
  },
  {
    id: "hierarquia_exposicao_enfrentamento",
    code: "F24",
    title: "Hierarquia de Exposição e Enfrentamento (Resolut. e Enfrent. - T130)",
    description: "Ferramenta Integradora nº 27 baseada no modelo estruturado de Habilidades Psicológicas. Auxilia o paciente a listar circunstâncias problemáticas, pendências, estressores ou aversões e ordená-los de forma métrica a partir de notas de Frequência, Incômodo e Dificuldade (F-I-D), permitindo planejar um enfrentamento gradual, seguro e sistemático.",
    category: "resolut_enfrent",
    duration: "15-20 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["HP de Autorregulação Emocional", "Resolutividade de Enfrentamento", "Enfrentamento Ativo", "Dessensibilização Sistemática", "Exposição Gradual"],
    status: "ready",
    icon: "ListOrdered",
    scoringInfo: "Calcula o Índice de Carga de Evitação Ativa e o Índice de Resolutividade Prática, organizando as circunstâncias de forma priorizada para micro-exposições integradas."
  },
  {
    id: "analise_criticos",
    code: "F25",
    title: "Análise dos Tipos de Críticos (Imunidade social - T150)",
    description: "Mapeia a influência dos julgamentos alheios e categoriza os críticos do paciente em 4 quadrantes cognitivos: Ignorante, Repetidor, Pesquisador e Pensante. Auxilia no desenvolvimento de defesas saudáveis contra distorções externas e calcula o Índice de Imunidade Social (IIS) para robustez emocional e HP de autoeficácia ativa.",
    category: "imunidade_social",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Imunidade Social", "Autoconfiança Prática", "Regulação de Feedback", "Diferenciação do Self", "Resiliência Interpessoal"],
    status: "ready",
    icon: "ShieldAlert",
    scoringInfo: "Calcula o Índice de Imunidade Social (IIS), ponderando a imunidade ao ruído insolúvel (críticos ignorantes/repetidores) e o processamento de críticas refinadas (críticos pesquisadores/pensantes)."
  },
  {
    id: "espectro_cognitivo",
    code: "F26",
    title: "Alternativas no Espectro Cognitivo (Imunidade social - T157)",
    description: "Técnica clínica que expande o pensamento polarizado desenhando um espectro de cinco perspectivas para a mesma situação: Catastrofismo, Pessimismo, Realismo, Otimismo e Utopismo. Ensina o paciente a identificar onde sua crença automática se posiciona e treinar flexibilidade cognitiva e robustez diante de reações e julgamentos do ambiente social externo.",
    category: "imunidade_social",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Espectro Cognitivo", "Flexibilidade Mental", "Realismo Prático", "Otimismo Saudável", "Descatastrofização", "Identificação de Crenças", "Imunidade Social"],
    status: "ready",
    icon: "Sliders",
    scoringInfo: "Calcula o Índice de Equilíbrio do Espectro (IEE) com base na amplitude de perspectivas preenchidas, na acurácia da localização da crença atual e na convicção na lente Realístico-Otimista associando fatos com esperança ativa."
  },
  {
    id: "exame_duplo_vantagens",
    code: "F27",
    title: "Exame Duplo de Vantagens e Desvantagens (Autocontrole - T177)",
    description: "Auxilia o paciente na tomada de decisões e resolução de conflitos ambivalentes entre duas alternativas de ação. Aplica a HP de Raciocínio Realistamente Otimista e Autocontrole filtrando fantasias e idealizações, quantificando o peso emocional/racional (1-5) dos prós e contras para obter um saldo líquido de decisão matemático.",
    category: "autocontrole",
    duration: "15-20 min",
    targetGroup: "Adultos, Casais & Adolescentes",
    skillsEvaluated: ["Raciocínio Realisticamente Otimista", "Tomada de Decisão", "Balanço Decisório", "Filtragem de Fantasias", "Resolutividade de Problemas", "Enfrentamento Ativo", "Autocontrole"],
    status: "ready",
    icon: "Scale",
    scoringInfo: "Resulta no Cálculo do Saldo Decisório Líquido (SDL) para cada alternativa, pesando a relevância dos prós e contras reais com filtragem sistemática de pensamentos catastróficos ou utópicos."
  },
  {
    id: "acompanhamento_pdp",
    code: "F28",
    title: "Acompanhamento do PDP (Autocontrole - T181)",
    description: "Programa de Desenvolvimento Psicológico de 5 Fases para formação estruturada de Habilidades Psicológicas. Ensina noções fundamentais, motivação existencial, reestrutura raciocínios limitantes, elenca fontes de imersão e acompanha a conduta diária e rotina disciplinada de decolagem de produtividade.",
    category: "autocontrole",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Formação de HPs", "Autogestão de Repertório", "Terapia de 4ª Geração", "Monitoramento Clínico", "Resiliência Comportamental", "Autocontrole"],
    status: "ready",
    icon: "Clipboard",
    scoringInfo: "Calcula o progresso de estruturação e consolidação da HP com base no preenchimento das fases de motivação, reestruturação mental, imersões consumidas e práticas de exercícios diários."
  },
  {
    id: "acompanhamento_pme",
    code: "F28-B",
    title: "Acompanhamento do PME+PDP (Autocontrole - T180)",
    description: "Abordagem clínica completa e integrada. Combina o Processo de Modificação Esquemática (PME) de 8 etapas (para reabilitação vivencial e cognitiva de EIDs e lembranças traumáticas precoces) com o correspondente Processo de Desenvolvimento Psicológico (PDP) de 5 fases para sedimentar a HP-Sinergética adaptativa correspondente no repertório ativo do paciente.",
    category: "autocontrole",
    duration: "20-25 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Reabilitação Esquemática", "Desenvolvimento de HPs", "Reparentalização Limitada", "Terapia de Esquemas", "Exercícios Clínicos", "Autocontrole"],
    status: "ready",
    icon: "Heart",
    scoringInfo: "Calcula o progresso combinado: 50% para a reabilitação do passado (8 fases do PME) e 50% para o estabelecimento de novas competências e práticas diárias (23 checkpoints de PDP)."
  },
  {
    id: "mentalidades_hedonismo_responsavel",
    code: "F29",
    title: "Mentalidades Saudáveis: Hedonismo Responsável (T29)",
    description: "Ferramenta Integradora nº 29 baseada na HP de Hedonismo Responsável. Auxilia o paciente a cultivar micro-regras e pensamentos libertadores e autorreguladores focados em vitalidade, prazer ponderado e equilíbrio saudável entre deveres e gratificações genuínas.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Hedonismo Responsável", "Equilíbrio de Vida", "Auto-gratificação Saudável", "Mitigação de Culpa", "Dever vs Prazer"],
    status: "ready",
    icon: "Heart",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_autoconhecimento",
    code: "F30",
    title: "Mentalidades Saudáveis: Autoconhecimento (T30)",
    description: "Ferramenta Integradora nº 30 baseada na HP de Autoconhecimento. Promove o refinamento da auto-observação, ajudando o paciente a aceitar limites, discriminar sua própria história de condicionamentos e organizar um olhar compreensivo sobre sua subjetividade.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Autoconhecimento", "Auto-observação", "Contextualização Histórica", "Discriminação de Comportamento", "Humildade Psicológica"],
    status: "ready",
    icon: "Scale",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_autoestima",
    code: "F31",
    title: "Mentalidades Saudáveis: Autoestima (T31)",
    description: "Ferramenta Integradora nº 31 baseada na HP de Autoestima. Propõe a consolidação da autoimagem positiva, o desenvolvimento do amor-próprio e da autoconfiança por meio do registro fático de experiências bem-sucedidas e do autocuidado continuado.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Autoestima", "Amor-Próprio", "Autoconfiança", "Autocuidado", "Autoaceitação Progressiva"],
    status: "ready",
    icon: "Award",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_raciocinio_otimista",
    code: "F32",
    title: "Mentalidades Saudáveis: Raciocínio Realistamente Otimista (T32)",
    description: "Ferramenta Integradora nº 32 baseada na HP de Raciocínio Realistamente Otimista. Combate visões catastróficas, polarizadas ou excessivamente utópicas, capacitando o paciente a ancorar certezas em fatos reais sem abrir mão da esperança ativa.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Raciocínio Realistamente Otimista", "Flexibilidade Prática", "Análise de Fatos", "Esperança Ativa", "Descatastrofização Integrada"],
    status: "ready",
    icon: "Sliders",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_autorregulacao_emocional",
    code: "F33",
    title: "Mentalidades Saudáveis: Autorregulação Emocional (T33)",
    description: "Ferramenta Integradora nº 33 baseada na HP de Autorregulação Emocional. Fornece âncoras cognitivas para apoiar o paciente diante de crises emocionais, ensinando a tolerar dores temporárias e a frear impulsos e compulsões nocivas.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Autorregulação Emocional", "Tolerância ao Estresse", "Desaquecimento Emocional", "Controle de Impulsos", "Significação de Sofrimentos"],
    status: "ready",
    icon: "Activity",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_imunidade_social",
    code: "F34",
    title: "Mentalidades Saudáveis: Imunidade Social (T34)",
    description: "Ferramenta Integradora nº 34 baseada na HP de Imunidade Social. Fortalece o senso de autonomia pessoal em relação às pressões do ambiente escolar e social, blindando o paciente contra piadas, críticas desproporcionais e a dependência tóxica de aprovação externa.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Imunidade Social", "Filtro de Críticas", "Autoaceitação Despida", "Neutralidade Reativa", "Convictabilidade Firme"],
    status: "ready",
    icon: "ShieldAlert",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_resolutividade_enfrentamento",
    code: "F35",
    title: "Mentalidades Saudáveis: Resolutividade e Enfrentamento (T35)",
    description: "Ferramenta Integradora nº 35 baseada na HP de Resolutividade e Enfrentamento. Estimula uma postura ativa e voltada à resolução de problemas, ensinando o paciente a diversificar tentativas, assumir riscos calculados e encarar dificuldades como degraus de aprendizado.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Resolutividade", "Enfrentamento de Problemas", "Variabilidade Comportamental", "Orientação Ativa", "Medidas de Contingência"],
    status: "ready",
    icon: "Activity",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_autocontrole",
    code: "F36",
    title: "Mentalidades Saudáveis: Autocontrole (T36)",
    description: "Ferramenta Integradora nº 36 baseada na HP de Autocontrole. Concentra-se no planejamento focado, disciplina sequencial e na substituição eficiente de impulsos imediatistas por rotinas estruturadas que produzem prosperidade e decolagem de produtividade.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Autocontrole", "Organização Prática", "Planejamento e Rotina", "Disciplina Ativa", "Produtividade Saudável"],
    status: "ready",
    icon: "Sliders",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_sociabilidade",
    code: "F37",
    title: "Mentalidades Saudáveis: Sociabilidade (T37)",
    description: "Ferramenta Integradora nº 37 baseada na HP de Sociabilidade. Facilita o cultivo de relacionamentos interpessoais saudáveis por meio da assertividade de comunicação, do pedido direto e da compreensão das opiniões e silêncios alheios.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Sociabilidade", "Comunicação Assertiva", "Abertura ao Diálogo", "Habilidades Verbais", "Interpessoalidade Ponderada"],
    status: "ready",
    icon: "Users",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  },
  {
    id: "mentalidades_sensibilidade_social",
    code: "F38",
    title: "Mentalidades Saudáveis: Sensibilidade Social (T38)",
    description: "Ferramenta Integradora nº 38 baseada na HP de Sensibilidade Social. Desenvolve a empatia e a valorização das necessidades humanas, encorajando o paciente e cultivando compaixão e altruísmo orientados ao enriquecimento interpessoal sutil.",
    category: "mentalidades",
    duration: "10-15 min",
    targetGroup: "Adultos & Adolescentes",
    skillsEvaluated: ["Sensibilidade Social", "Empatia Integral", "Altruísmo Ativo", "Solidariedade Social", "Compaixão Interpessoal"],
    status: "ready",
    icon: "Heart",
    scoringInfo: "Calcula a Taxa de Acolhimento Cognitivo baseada no número de mentalidades saudáveis selecionadas e monitora a aplicação da escrita analítica-terapêutica semanal."
  }
];

// Content of tests QUESTIONS
export const IDAI_QUESTIONS = [
  { id: "q1", text: "Sinto-me desanimado, sem esperança em relação ao futuro ou desamparado.", type: "scale", subscale: "Espectro Depressivo" },
  { id: "q2", text: "Apresento preocupações excessivas ou difíceis de controlar na maior parte do dia.", type: "scale", subscale: "Hiperativação Simpática" },
  { id: "q3", text: "Sinto palpitações, taquicardia ou formigamentos sem explicação médica.", type: "scale", subscale: "Hiperativação Simpática" },
  { id: "q4", text: "Perdi o interesse ou prazer em realizar atividades que antes eram prazerosas.", type: "scale", subscale: "Espectro Depressivo" },
  { id: "q5", text: "Sinto rigidez muscular, dor no pescoço/ombros ou dores tensionais associadas ao estresse.", type: "scale", subscale: "Tensão Somática" },
  { id: "q6", text: "Tenho pensamentos repetitivos de insuficiência ou culpa excessiva sobre as coisas.", type: "scale", subscale: "Espectro Depressivo" },
  { id: "q7", text: "Dificuldades para pegar no sono, acordar no meio da noite ou agitação noturna.", type: "scale", subscale: "Tensão Somática" },
  { id: "q8", text: "Sensação constante de sobressalto, susto fácil ou nervosismo à flor da pele.", type: "scale", subscale: "Hiperativação Simpática" },
  { id: "q9", text: "Falta de energia ou fadiga física pesada mesmo sem grande esforço físico recente.", type: "scale", subscale: "Tensão Somática" },
  { id: "q10", text: "Sinto uma névoa mental constante ou extrema dificuldade para tomar decisões corriqueiras.", type: "scale", subscale: "Espectro Depressivo" }
];

export const EFCA_QUESTIONS = [
  { id: "e1", text: "Quando tenho sentimentos difíceis de lidar, costumo tentar evitá-los a todo custo.", subscale: "Esquiva Experiencial" },
  { id: "e2", text: "Fico tão preso a pensamentos de autocrítica que me sinto incapaz de agir no presente.", subscale: "Fusão Cognitiva" },
  { id: "e3", text: "Consigo identificar o que é realmente importante para mim e agir de acordo, mesmo sob ansiedade.", subscale: "Compromisso com Valores", reversed: true },
  { id: "e4", text: "Evito atividades importantes por receio de que elas gerem sofrimento, vergonha ou nervosismo.", subscale: "Esquiva Experiencial" },
  { id: "e5", text: "Consigo observar meus pensamentos negativos sem tomá-los como verdades absolutas sobre quem sou.", subscale: "Fusão Cognitiva", reversed: true },
  { id: "e6", text: "Minhas decisões de vida são guiadas por meus valores fundamentais, e não pelos meus medos momentâneos.", subscale: "Compromisso com Valores", reversed: true },
  { id: "e7", text: "Luto freneticamente para afastar memórias dolorosas ou sensações que me trazem desconforto.", subscale: "Esquiva Experiencial" },
  { id: "e8", text: "Sinto-me escravizado pelas minhas ruminações do passado e antecipações fóbicas do futuro.", subscale: "Fusão Cognitiva" }
];
